---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ruby-sample-web-deployment"
  namespace: "default"
  labels:
    app: "ruby-sample-web"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ruby-sample-web"
  template:
    metadata:
      labels:
        app: "ruby-sample-web"
    spec:
      containers:
      - name: "ruby-sample-web"
        image: "gcr.io/fiery-surf-258805/ruby-sample-web-image:latest"

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ruby-sample-web-hpa-socs"
  namespace: "default"
  labels:
    app: "ruby-sample-web"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ruby-sample-web-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80


