---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-sample-web-deployment
  namespace: default
  labels:
    app: ruby-sample-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby-sample-web
  template:
    metadata:
      labels:
        app: ruby-sample-web
    spec:
      containers:
      - name: ruby-sample-web
        image: gcr.io/fiery-surf-258805/ruby-sample-web-image:latest
        ports:
          - containerPort: 3000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ruby-sample-web-hpa-socs
  namespace: default
  labels:
    app: ruby-sample-web
spec:
  scaleTargetRef:
    kind: Deployment
    name: ruby-sample-web-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ruby-sample-web-service
spec:
  selector:
    app: ruby-sample-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: NodePort

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ruby-sample-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: ruby-sample-web-service
    servicePort: 8080
#  rules:
#    - http:
#        paths:
#          - path: /welcome/index
#            backend:
#              serviceName: ruby-sample-web-service
#              servicePort: 8080
